# Generated by Django 4.0.4 on 2022-06-11 03:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(upload_to='Course Thumbnails', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'jpg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='entranceexam',
            name='exam',
            field=models.FileField(upload_to='Entrance Exams', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='week',
            name='book',
            field=models.FileField(upload_to='Weekly Books', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='week',
            name='thumbnail',
            field=models.ImageField(upload_to='Week Thumbnails', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'jpg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='week',
            name='video',
            field=models.FileField(upload_to='Weely Lessons', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])]),
        ),
    ]
