# Generated by Django 4.0.4 on 2022-06-08 03:46

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='FieldOfStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Architecture', 'Architecture'), ('Biology', 'Biology'), ('Biological Laboratory Science', 'Biological Laboratory Science'), ('Bio-Medical Engineering', 'Bio-Medical Engineering'), ('Bio-systems Engineering', 'Bio-systems Engineering'), ('Biotechnology', 'Biotechnology'), ('Chemistry', 'Chemistry'), ('Chemical Engineering', 'Chemical Engineering'), ('Construction and Building Technology', 'Construction and Building Technology'), ('Civil Engineering', 'Civil Engineering'), ('Computer Engineering', 'Computer Engineering'), ('Computer Science', 'Computer Science'), ('Civics & Ethics', 'Civics & Ethics'), ('English language and Literature', 'English language and Literature'), ('Health and Physical Education', 'Health and Physical Education'), ('Information Science', 'Information Science'), ('Information Systems', 'Information Systems'), ('Information Technology', 'Information Technology'), ('Mathematics', 'Mathematics'), ('Management Information Systems', 'Management Information Systems'), ('Physics', 'Physics'), ('Sport Management', 'Sport Management'), ('Sport Science', 'Sport Science'), ('Software Engineering', 'Software Engineering')], max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Addis Ababa University', 'Addis Ababa University'), ('Mekelle University', 'Mekelle University'), ('Bahir Dar University', 'Bahir Dar University'), ('Jimma University', 'Jimma University'), ('University of Gondar', 'University of Gondar'), ('Haramaya University (Alemaya)', 'Haramaya University (Alemaya)'), ('Hawassa University (Debub University)', 'Hawassa University (Debub University)'), ('Arba Minch University', 'Arba Minch University'), ('Debre Markos University', 'Debre Markos University'), ('Wollo University', 'Wollo University'), ('Wolaita Sodo University', 'Wolaita Sodo University'), ('Aksum University', 'Aksum University'), ('Arsi University', 'Arsi University'), ('Adama Science & Technology University', 'Adama Science & Technology University'), ('Kebri Dehar University', 'Kebri Dehar University'), ('Addis Ababa Science and Technology University', 'Addis Ababa Science and Technology University'), ('Wachemo University', 'Wachemo University'), ('Addis Ababa Institute of Technology', 'Addis Ababa Institute of Technology'), ('Debre Berhan University', 'Debre Berhan University'), ('Ambo University', 'Ambo University'), ('Dire Dawa University', 'Dire Dawa University'), ('Welkete University', 'Welkete University'), ('Ethiopian Civil Service University', 'Ethiopian Civil Service University'), ('Saint Mary`s University College Ethiopia', 'Saint Mary`s University College Ethiopia'), ('Ethiopian Institute of Architecture', 'Ethiopian Institute of Architecture'), ('Adigrat University', 'Adigrat University'), ('Mizan Tepi University', 'Mizan Tepi University'), ('Assosa University', 'Assosa University'), ('Dilla University', 'Dilla University'), ('Madawalabu University', 'Madawalabu University'), ('Jigjiga University', 'Jigjiga University'), ('Wollega University', 'Wollega University'), ('Micro Link Information Technology College', 'Micro Link Information Technology College'), ('Kotebe Metropolitan University', 'Kotebe Metropolitan University'), ('Samara University', 'Samara University'), ('Addis Continental Institute of Public Health', 'Addis Continental Institute of Public Health'), ('Rift Valley University', 'Rift Valley University'), ('Bule Hora University', 'Bule Hora University'), ('Western University College Ethiopia', 'Western University College Ethiopia'), ('Mettu University', 'Mettu University'), ('Hope University College', 'Hope University College'), ('Meserete Kristos College', 'Meserete Kristos College'), ('Addis Ababa Medical University College Hargiesa', 'Addis Ababa Medical University College Hargiesa'), ('Woldia University', 'Woldia University'), ('GAGE University College', 'GAGE University College'), ('Unity University College', 'Unity University College'), ('Haramaya University Haramaya Institute of Technology', 'Haramaya University Haramaya Institute of Technology'), ('CPU College', 'CPU College'), ('Ethiopian Graduate School of Theology', 'Ethiopian Graduate School of Theology'), ('HiLCoE School of Computer Science and Technology College', 'HiLCoE School of Computer Science and Technology College'), ('Defence Engineering College', 'Defence Engineering College'), ('International Leadership Institute', 'International Leadership Institute'), ('Oda Bultum University', 'Oda Bultum University'), ('Admas University Ethiopia', 'Admas University Ethiopia'), ('Injibara University', 'Injibara University'), ('Ethiopian Management Institute', 'Ethiopian Management Institute'), ('Oromia State University', 'Oromia State University'), ('Myungsung Medical College', 'Myungsung Medical College'), ('Federal TVET Institute', 'Federal TVET Institute'), ('Holy Trinity University', 'Holy Trinity University'), ('Catering and Tourism Training Institute Addis Ababa', 'Catering and Tourism Training Institute Addis Ababa'), ('Addis Ababa University College of Commerce', 'Addis Ababa University College of Commerce'), ('Ethiopia Adventist College', 'Ethiopia Adventist College'), ('St Paul`s Hospital Millennium Medical College', 'St Paul`s Hospital Millennium Medical College'), ('PESC College Addis Ababa', 'PESC College Addis Ababa'), ('Tech Zone Engineering & Business College', 'Tech Zone Engineering & Business College'), ('Sante Medical College', 'Sante Medical College'), ('Royal College Ethiopia', 'Royal College Ethiopia'), ('Addis Ababa Medical and Business College', 'Addis Ababa Medical and Business College'), ('Sri Sai College', 'Sri Sai College'), ('Universal Medical Collage', 'Universal Medical Collage')], max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('phone', models.CharField(max_length=13)),
                ('profile_picture', models.ImageField(upload_to='Profile Pictures')),
                ('academic_level', models.CharField(choices=[('Lower School', 'Lower School'), ('Elementery School', 'Elementery School'), ('High School', 'High School'), ('Preparatory School', 'Preparatory School')], max_length=20)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
            bases=('a_user.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('phone', models.CharField(max_length=13)),
                ('profile_picture', models.ImageField(upload_to='Profile Pictures')),
                ('description', models.TextField(default='')),
                ('academic_completion_university', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='a_user.university')),
                ('field_of_study', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='a_user.fieldofstudy')),
            ],
            options={
                'verbose_name': 'Instructor',
                'verbose_name_plural': 'Instructors',
            },
            bases=('a_user.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
