# Generated by Django 4.0.4 on 2022-06-11 03:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_user', '0002_user_is_instructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='profile_picture',
            field=models.ImageField(upload_to='Profile Pictures', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'jpg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_picture',
            field=models.ImageField(upload_to='Profile Pictures', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'jpg', 'png'])]),
        ),
    ]
